theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker
  - searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking
  - save table contextmenu directionality template paste textcolor
toolbar:
  - insertfile undo redo | fontsizeselect | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor
